services:
  app:
    build: .
    # ports:
    #   - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      # JSONファイルの保存先をホストと共有
      - ./backend/exports:/app/exports
      # 画像アップロードの保存先をホストと共有
      - ./backend/public/uploads:/tracker/public/uploads
    environment:
      - NODE_ENV=production
      - TZ=Asia/Tokyo
      # MongoDB認証情報を追加
      - MONGO_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - tracker_network
      - default
    restart: unless-stopped
    
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      # データを削除
      #- mongo-data:/data/db
      # ホストの./dataディレクトリにデータを永続化
      - ./data:/data/db
    environment:
      - TZ=Asia/Tokyo
      # MongoDB認証を有効化
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - default
    restart: unless-stopped

networks:
  tracker_network:
    external: true